name: SkyWalking APM Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: SkyWalking APM Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: |
          ./mvnw clean package -Dmaven.test.skip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: apache-skywalking-apm-bin
          path: ${{ github.workspace }}/dist/apache-skywalking-apm-bin.tar.gz
